# Generated by Django 4.0.4 on 2022-05-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_instructors_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.courses'),
        ),
    ]
